---
name: CI
'on': push
jobs:
  build:
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch tags
      run: "  git fetch --tags\n"
    - name: Initialize mbedtls submodule
      run: |2
          cd third_party/esp-idf
          git submodule update --init
          git submodule update --init components/mbedtls
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Get Go paths
      run: |2
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      id: go-cache-paths
    - name: HMM
      run:
        echo ${{ steps.go-cache-paths.go-build }}
        echo ${{ steps.go-cache-paths.go-mod }}
        echo "${{ steps.go-cache-paths.go-build }}"
        echo "${{ steps.go-cache-paths.go-mod }}"
    - name: Go build
      uses: actions/cache@v2
      with:
        path: "${{ steps.go-cache-paths.go-build }}"
        key: Linux-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: Linux-go-build
    - name: Go mod
      uses: actions/cache@v2
      with:
        path: "${{ steps.go-cache-paths.go-mod }}"
        key: Linux-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: Linux-go-build
    - name: Apt-get update
      run: "  sudo apt-get update\n"
    - name: Apt-get install ccache
      run: "  sudo apt-get install ccache\n"
    - name: Create timestamp
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
      id: timestamp_step
      shell: cmake -P {0}
    - name: Ccache
      uses: actions/cache@v2
      with:
        path: "${{ github.workspace }}/.ccache"
        key: Linux-ccache-${{ steps.timestamp_step.timestamp }}
        restore-keys: Linux-ccache
    - name: Apt-get install ninja-build gcc-multilib g++-multilib
      run: "  sudo apt-get install ninja-build gcc-multilib g++-multilib\n"
    - name: Make
      run: |-
        make all
        make CROSS_ARCH=host32 all-cross
    runs-on: ubuntu-latest
